export const GET_COURSE_REQUEST = "GET_COURSE_REQUEST";
export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const GET_COURSE_FAILURE = "GET_COURSE_FAILURE";

export const GET_LATESTENROLLMENT_REQUEST = "GET_LATESTENROLLMENT_REQUEST";
export const GET_LATESTENROLLMENT_SUCCESS = "GET_LATESTENROLLMENT_SUCCESS";
export const GET_LATESTENROLLMENT_FAILURE = "GET_LATESTENROLLMENT_FAILURE";

export const GET_BESTSTUDENTS_REQUEST = "GET_BESTSTUDENTS_REQUEST";
export const GET_BESTSTUDENTS_SUCCESS = "GET_BESTSTUDENTS_SUCCESS";
export const GET_BESTSTUDENTS_FAILURE = "GET_BESTSTUDENTS_FAILURE";
